name: github action CI/CD 테스트용
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write
  pull-requests: write

jobs:
  deployment:
    name: Deployment-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install
        run: npm install

      - name: Run build
        run: npm run build

      - name: configure github pages
        uses: actions/configure-pages@v2
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Format comment message
        id: format_comment_message
        uses: actions/github-script@v3
        with:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          script: |
          
            const deployURL = 'https://phoebe.github.io/page-test/';
            const comments = [
              `## Deploy Preview`,
              `🔥 **check your project preview here!** : `
            ].join('\n');
            
            core.setOutput('comment', comments);
            
      - name: comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: |
            ${{ steps.format_comment_message.outputs.comment}}[${{ steps.deployment.outputs.page_url }}](${{ steps.deployment.outputs.page_url }})
